apiVersion: apps/v1
kind: Deployment

metadata:
  name: node-deploy

spec:
  replicas: 3

  selector:
    matchLabels:
      app: node

  template:
    metadata:
      labels:
        app: node

    spec:
      containers:
        - name: node
          image: shindevaibhavi11/mern-backend:v1

          ports:
            - containerPort: 3000

          envFrom:
            - configMapRef:
                name: node-config
